import { Area, Translations, Shop, SalesRoute, Product } from './types';

export const INITIAL_AREAS: Area[] = [
  { id: '1', name: 'Kallyanpur', assignedDay: 'শনিবার' },
  { id: '2', name: 'Majgram', assignedDay: 'রবিবার' },
  { id: '3', name: 'Shilaidah', assignedDay: 'সোমবার' },
  { id: '4', name: 'Arpara', assignedDay: 'মঙ্গলবার' },
  { id: '5', name: 'Mirzapur', assignedDay: 'বুধবার' },
  { id: '6', name: 'Banani', assignedDay: 'বৃহস্পতিবার' },
  { id: '7', name: 'Gulshan', assignedDay: 'শুক্রবার' },
  { id: '8', name: 'Dhanmondi', assignedDay: 'শনিবার' },
  { id: '9', name: 'Uttara', assignedDay: 'রবিবার' },
  { id: '10', name: 'Mirpur', assignedDay: 'সোমবার' },
  { id: '11', name: 'Kumarkhali', assignedDay: 'মঙ্গলবার' },
  { id: '12', name: 'Kushtia', assignedDay: 'বুধবার' }
];

export const INITIAL_SHOPS: Shop[] = [
  {
    id: 's1',
    name: 'Bhai Bhai Enterprise',
    ownerName: 'Abul Hasnat',
    phone: '01711223344',
    subArea: 'Technical Junction',
    location: { lat: 23.7806, lng: 90.3521 }, // Kallyanpur Area
    areaId: '1',
    createdAt: Date.now()
  },
  {
    id: 's2',
    name: 'Janata Store',
    ownerName: 'Moklesur Rahman',
    phone: '01822334455',
    subArea: 'South Block',
    location: { lat: 23.7812, lng: 90.3535 }, // Kallyanpur Area
    areaId: '1',
    createdAt: Date.now()
  },
  {
    id: 's3',
    name: 'Mayer Doa General Store',
    ownerName: 'Sujon Ahmed',
    phone: '01933445566',
    subArea: 'Market Corner',
    location: { lat: 23.9482, lng: 89.1234 }, // Majgram Area
    areaId: '2',
    createdAt: Date.now()
  }
];

export const DEMO_ROUTES: SalesRoute[] = [
  {
    id: 'timeline-demo-kumarkhali',
    date: '23/05/2024',
    areaId: '11',
    startTime: Date.now() - 172800000,
    endTime: Date.now() - 172800000 + 3600000,
    path: [
      { lat: 23.8647, lng: 89.2467 }, // Start: Kumarkhali
      { lat: 23.8680, lng: 89.2300 },
      { lat: 23.8750, lng: 89.2100 },
      { lat: 23.8850, lng: 89.1800 },
      { lat: 23.8950, lng: 89.1500 },
      { lat: 23.9010, lng: 89.1204 }  // End: Kushtia
    ],
    stops: [
      { 
        location: { lat: 23.8647, lng: 89.2467 }, 
        areaName: 'Kumarkhali Bus Stand', 
        stopNumber: 1, 
        timestamp: Date.now() - 172800000 
      },
      { 
        location: { lat: 23.8850, lng: 89.1800 }, 
        areaName: 'Lalon Shah Bridge Point', 
        stopNumber: 2, 
        timestamp: Date.now() - 172800000 + 1500000 
      },
      { 
        location: { lat: 23.9010, lng: 89.1204 }, 
        areaName: 'Kushtia Town Center', 
        stopNumber: 3, 
        timestamp: Date.now() - 172800000 + 3600000 
      }
    ]
  }
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'p1',
    name: 'Fresh Milk 1L',
    weight: '1L',
    price: 90,
    stock: 100,
    category: 'Dairy',
    status: 'Active',
    createdAt: Date.now()
  },
  {
    id: 'p2',
    name: 'Brown Bread 400g',
    weight: '400g',
    price: 55,
    stock: 50,
    category: 'Bakery',
    status: 'Active',
    createdAt: Date.now()
  },
  {
    id: 'p3',
    name: 'Organic Eggs (12pcs)',
    weight: '1 Dozen',
    price: 150,
    stock: 30,
    category: 'Poultry',
    status: 'Active',
    createdAt: Date.now()
  },
  {
    id: 'p4',
    name: 'Pure Honey 500g',
    weight: '500g',
    price: 450,
    discount: 10,
    stock: 20,
    category: 'Groceries',
    status: 'Active',
    createdAt: Date.now()
  }
];

export const TRANSLATIONS: Translations = {
  appTitle: { en: 'FieldPro Assistant', bn: 'ফিল্ডপ্রো অ্যাসিস্ট্যান্ট' },
  dashboard: { en: 'Dashboard', bn: 'ড্যাশবোর্ড' },
  map: { en: 'Map', bn: 'মানচিত্র' },
  shops: { en: 'Shops', bn: 'দোকানসমূহ' },
  history: { en: 'History', bn: 'ইতিহাস' },
  settings: { en: 'Settings', bn: 'সেটিংস' },
  addShop: { en: 'Add New Shop', bn: 'নতুন দোকান যোগ করুন' },
  editShop: { en: 'Edit Shop', bn: 'দোকান সম্পাদনা' },
  shopName: { en: 'Shop Name', bn: 'দোকানের নাম' },
  ownerName: { en: 'Owner Name', bn: 'মালিকের নাম' },
  mobile: { en: 'Mobile Number', bn: 'মোবাইল নম্বর' },
  area: { en: 'Area', bn: 'এলাকা' },
  subArea: { en: 'Sub Area', bn: 'সাব এরিয়া' },
  selectArea: { en: 'Select Area', bn: 'এলাকা নির্বাচন করুন' },
  photo: { en: 'Owner Photo', bn: 'মালিকের ছবি' },
  save: { en: 'Save', bn: 'সংরক্ষণ করুন' },
  cancel: { en: 'Cancel', bn: 'বাতিল করুন' },
  trackingOn: { en: 'Tracking Active', bn: 'ট্র্যাকিং চালু আছে' },
  trackingOff: { en: 'Start Tracking', bn: 'ট্র্যাকিং শুরু করুন' },
  nearbyAlert: { en: 'Nearby Shop Alert!', bn: 'কাছাকাছি দোকান!' },
  within100m: { en: 'is within 20 meters.', bn: '২০ মিটারের মধ্যে আছে।' },
  search: { en: 'Search shops, owners or areas...', bn: 'দোকান, মালিক বা এলাকা খুঁজুন...' },
  noShops: { en: 'No shops found.', bn: 'কোনো দোকান পাওয়া যায়নি।' },
  routes: { en: 'Saved Routes', bn: 'সংরক্ষিত রুটসমূহ' },
  getDirections: { en: 'Get Directions', bn: 'রাস্তা দেখুন' },
  stopNavigation: { en: 'Stop Navigation', bn: 'ন্যাভিগেশন বন্ধ করুন' },
  distance: { en: 'Distance', bn: 'দূরত্ব' },
  turn_left: { en: 'Turn Left', bn: 'বামে মোড় নিন' },
  turn_right: { en: 'Turn Right', bn: 'ডানে মোড় নিন' },
  go_straight: { en: 'Go Straight', bn: 'সোজা যান' },
  slight_left: { en: 'Slight Left', bn: 'সামান্য বামে' },
  slight_right: { en: 'Slight Right', bn: 'সামান্য ডানে' },
  u_turn: { en: 'Make a U-Turn', bn: 'ইউ-টার্ন নিন' },
  arrived: { en: 'You have arrived!', bn: 'আপনি পৌঁছে গেছেন!' },
  nearbyShops: { en: 'Nearby Shops (20m)', bn: 'কাছাকাছি দোকানসমূহ (২০ মি.)' },
  noNearbyShops: { en: 'No shops within 20m.', bn: '২০ মিটারের মধ্যে কোনো দোকান নেই।' },
  spotRange: { en: 'Spot Detection Range', bn: 'স্পট শনাক্তকরণের রেঞ্জ' },
  rangeDescription: { en: 'Set how close you need to be to identify a shop.', bn: 'দোকান শনাক্ত করার জন্য আপনি কতটা কাছে থাকবেন তা নির্ধারণ করুন।' },
  meters: { en: 'meters', bn: 'মিটার' },
  visited: { en: 'Visited', bn: 'ভিজিট সম্পন্ন' },
  markVisited: { en: 'Mark Visit Complete', bn: 'ভিজিট সম্পন্ন করুন' },
  unmarkVisited: { en: 'Unmark as Visited', bn: 'ভিজিট বাতিল করুন' },
  quickAccess: { en: 'Quick Access', bn: 'কুইক অ্যাক্সেস' },
  productCatalog: { en: 'Product Catalog', bn: 'পণ্য তালিকা' },
  orderTaking: { en: 'Order System', bn: 'অর্ডার সিস্টেম' },
  dailySummary: { en: 'Daily Summary', bn: 'দৈনিক সারাংশ' },
  followUpReminder: { en: 'Reminders', bn: 'রিমাইন্ডার' },
  smartRoute: { en: 'Smart Route', bn: 'স্মার্ট রুট' },
  targetProgress: { en: 'Target Progress', bn: 'লক্ষ্য ও অগ্রগতি' },
  targetVsAchievement: { en: 'Target vs Achievement', bn: 'টার্গেট বনাম অর্জন' },
  performance: { en: 'Performance', bn: 'পারফরম্যান্স' },
  analytics: { en: 'Reports', bn: 'রিপোর্ট' },
  dealerDistributor: { en: 'Dealer / Distributor', bn: 'ডিলার / ডিস্ট্রিবিউটর' },
  catalogSection: { en: 'Catalog & Inventory', bn: 'ক্যাটালগ ও ইনভেন্টরি' },
  productName: { en: 'Product Name', bn: 'পণ্যের নাম' },
  weightUnit: { en: 'Weight / Unit', bn: 'ওজন / ইউনিট' },
  price: { en: 'Price', bn: 'মূল্য' },
  addProduct: { en: 'Add Product', bn: 'পণ্য যোগ করুন' },
  editProduct: { en: 'Edit Product', bn: 'পণ্য সম্পাদনা' },
  deleteProduct: { en: 'Delete Product', bn: 'পণ্য মুছুন' },
  confirmDeleteProduct: { en: 'Delete this product from catalog?', bn: 'ক্যাটালগ থেকে এই পণ্যটি মুছতে চান?' },
  productReplacement: { en: 'Product Replacement', bn: 'পণ্য পরিবর্তন' },
  replaceProduct: { en: 'Replace Product', bn: 'পণ্য পরিবর্তন করুন' },
  returnedProduct: { en: 'Returned Product (Expired/Damaged)', bn: 'ফেরত পণ্য (মেয়াদোত্তীর্ণ/ক্ষতিগ্রস্ত)' },
  replacedProduct: { en: 'Replaced Product (New)', bn: 'পরিবর্তিত পণ্য (নতুন)' },
  quantity: { en: 'Quantity', bn: 'পরিমাণ' },
  addReplacement: { en: 'Add Replacement', bn: 'পরিবর্তন যোগ করুন' },
  replacementSection: { en: 'Replacement Details', bn: 'পরিবর্তন সংক্রান্ত তথ্য' },
  noCharge: { en: 'No additional charge for replacements', bn: 'পরিবর্তিত পণ্যের জন্য কোনো অতিরিক্ত টাকা লাগবে না' },
  selectProduct: { en: 'Select Product', bn: 'পণ্য নির্বাচন করুন' },
  dues: { en: 'Dues', bn: 'বকেয়া' },
  totalDues: { en: 'Total Dues', bn: 'মোট বকেয়া' },
  collectPayment: { en: 'Collect Payment', bn: 'টাকা আদায়' },
  paymentAmount: { en: 'Payment Amount', bn: 'আদায়ের পরিমাণ' },
  paymentMethod: { en: 'Payment Method', bn: 'আদায়ের মাধ্যম' },
  cash: { en: 'Cash', bn: 'নগদ' },
  cheque: { en: 'Cheque', bn: 'চেক' },
  mfs: { en: 'MFS (bKash/Nagad)', bn: 'এমএফএস (বিকাশ/নগদ)' },
  paymentDate: { en: 'Payment Date', bn: 'আদায়ের তারিখ' },
  paymentHistory: { en: 'Payment History', bn: 'আদায়ের ইতিহাস' },
  addPayment: { en: 'Add Payment', bn: 'পেমেন্ট যোগ করুন' },
  noPayments: { en: 'No payments recorded.', bn: 'কোনো পেমেন্ট রেকর্ড নেই।' },
  viewHistory: { en: 'View History', bn: 'ইতিহাস দেখুন' },
  balance: { en: 'Balance', bn: 'ব্যালেন্স' },
  expenses: { en: 'Expenses', bn: 'খরচ' },
  addExpense: { en: 'Add Expense', bn: 'খরচ যোগ করুন' },
  expenseCategory: { en: 'Category', bn: 'ধরণ' },
  expenseAmount: { en: 'Amount', bn: 'পরিমাণ' },
  expenseDate: { en: 'Date', bn: 'তারিখ' },
  expenseDescription: { en: 'Description', bn: 'বিবরণ' },
  totalExpenses: { en: 'Total Expenses', bn: 'মোট খরচ' },
  fuel: { en: 'Fuel', bn: 'জ্বালানি' },
  food: { en: 'Food', bn: 'খাবার' },
  maintenance: { en: 'Maintenance', bn: 'রক্ষণাবেক্ষণ' },
  others: { en: 'Others', bn: 'অন্যান্য' },
  userProfile: { en: 'User Profile', bn: 'ইউজার প্রোফাইল' },
  userName: { en: 'User Name', bn: 'ব্যবহারকারীর নাম' },
  employeeId: { en: 'Employee ID', bn: 'এমপ্লয়ি আইডি' },
  designation: { en: 'Designation', bn: 'পদবী' },
  phoneNumber: { en: 'Phone Number', bn: 'ফোন নাম্বার' },
  editProfile: { en: 'Edit Profile', bn: 'প্রোফাইল সম্পাদনা' },
  darkMode: { en: 'Dark Mode', bn: 'ডার্ক মোড' },
  lightMode: { en: 'Light Mode', bn: 'লাইট মোড' },
  theme: { en: 'Theme', bn: 'থিম' },
  notificationSettings: { en: 'Notification Settings', bn: 'নোটিফিকেশন সেটিংস' },
  orderConfirmation: { en: 'Order Confirmation', bn: 'অর্ডার কনফার্মেশন' },
  targetReminder: { en: 'Target Reminder', bn: 'টার্গেট রিমাইন্ডার' },
  newShopDetection: { en: 'New Shop Detection', bn: 'নতুন শপ ডিটেকশন' },
  pushNotifications: { en: 'Push Notifications', bn: 'পুশ নোটিফিকেশন' },
  birthday: { en: 'Birthday', bn: 'জন্মদিন' },
  anniversary: { en: 'Anniversary', bn: 'প্রতিষ্ঠাবার্ষিকী' },
  specialDays: { en: 'Special Days', bn: 'বিশেষ দিনসমূহ' },
  upcomingSpecialDays: { en: 'Upcoming Special Days', bn: 'আসন্ন বিশেষ দিনসমূহ' },
  celebratingToday: { en: 'Celebrating Today', bn: 'আজকের উদযাপন' },
  manageShops: { en: 'Manage Shops', bn: 'দোকান ব্যবস্থাপনা' },
  deleteShop: { en: 'Delete Shop', bn: 'দোকান মুছুন' },
  confirmDeleteShop: { en: 'Are you sure you want to delete this shop?', bn: 'আপনি কি নিশ্চিত যে আপনি এই দোকানটি মুছতে চান?' },
  activePartner: { en: 'Active Partner', bn: 'অ্যাক্টিভ পার্টনার' },
  inactivePartner: { en: 'Inactive Partner', bn: 'ইনঅ্যাক্টিভ পার্টনার' },
  partnerStatus: { en: 'Partner Status', bn: 'পার্টনার স্ট্যাটাস' },
  routePlayback: { en: 'Route Playback', bn: 'রুট প্লেব্যাক' },
  play: { en: 'Play', bn: 'চালু করুন' },
  pause: { en: 'Pause', bn: 'থামান' },
  speed: { en: 'Speed', bn: 'গতি' },
  replay: { en: 'Replay', bn: 'আবার দেখুন' },
  managePlaces: { en: 'Manage Places', bn: 'স্থান ব্যবস্থাপনা' },
  addPlace: { en: 'Add Place', bn: 'স্থান যোগ করুন' },
  editPlace: { en: 'Edit Place', bn: 'স্থান সম্পাদনা' },
  placeName: { en: 'Place Name', bn: 'স্থানের নাম' },
  deletePlace: { en: 'Delete Place', bn: 'স্থান মুছুন' },
  confirmDeletePlace: { en: 'Are you sure you want to delete this place?', bn: 'আপনি কি নিশ্চিত যে আপনি এই স্থানটি মুছতে চান?' },
  competitorTracking: { en: 'Competitor Tracking', bn: 'প্রতিযোগী ট্র্যাকিং' },
  competitorName: { en: 'Competitor Name', bn: 'প্রতিযোগীর নাম' },
  offerDetails: { en: 'Offer Details', bn: 'অফারের বিবরণ' },
  addTrack: { en: 'Add Competitor Info', bn: 'প্রতিযোগীর তথ্য যোগ করুন' },
  noTracks: { en: 'No competitor info recorded.', bn: 'কোনো প্রতিযোগীর তথ্য রেকর্ড নেই।' },
  selectShop: { en: 'Select Shop', bn: 'দোকান নির্বাচন করুন' },
  shop: { en: 'Shop', bn: 'দোকান' }
};
